WebController/Controllers/DashboardController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System.Collections.Generic;
using System.Linq;
using MyNodes.Nodes;
using MyNodes.Users;
using MyNodes.WebController.Code;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.DashboardObserver)]
    public class DashboardController : Controller
    {
        const string MAIN_PANEL_ID = "Main";
        const string HOME_PANEL_ID = "Home";

        private UiNodesEngine engine = SystemController.uiNodesEngine;


        public IActionResult Index()
        {
            ViewBag.panelId = HOME_PANEL_ID;

            return View();
        }



        public IActionResult Panel(string id)
        {
            if (engine == null)
                return BadRequest();

            if (id == null || id == MAIN_PANEL_ID)
            {
                id = MAIN_PANEL_ID;
                ViewBag.panelName = "Main Panel";
            }
            else
            {
                PanelNode panel = engine.GetPanel(id);
                if (panel == null)
                    return NotFound();
                ViewBag.panelName = panel.Settings["Name"].Value;
            }

            ViewBag.panelId = id;
            return View("Index");
        }

        public IActionResult List()
        {
            if (engine == null)
                return BadRequest();

            ViewBag.showMainPanel = engine.GetUINodesForPanel(MAIN_PANEL_ID).Any();

            List<PanelNode> allPanels = engine.GetPanels();
            List<PanelNode> notEmptyPanels = new List<PanelNode>();
            foreach (var panel in allPanels)
            {
                if (engine.GetUINodesForPanel(panel.Id).Any())
                    notEmptyPanels.Add(panel);
            }

            return View(notEmptyPanels);
        }


        
        public IActionResult Chart(string id, string autoscroll, string style, string start, string end)
        {
            if (engine == null)
                return BadRequest();

            UiChartNode node = engine.GetUINode(id) as UiChartNode;
            if (node == null)
                return new NotFoundResult();

            ViewBag.autoscroll = autoscroll;

            if (style == null)
                style = node.Style;

            ViewBag.style = style;
            ViewBag.start = start ?? "0";
            ViewBag.end = end ?? "0";
            ViewBag.panelId = node.PanelId;

            return View(node);
        }
    }
}

WebController/Controllers/LogsController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNodes.Users;
using MyNodes.WebController.Code;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.LogsObserver)]

    public class LogsController: Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Show",new { id = "System"});
        }


        public IActionResult Show(string id)
        {
            ViewBag.LogType = id;
            ViewBag.PageName = id;

            switch (id)
            {
                case "GatewayState":
                    ViewBag.PageName = "Gateway State";
                    break;
                case "GatewayMessages":
                    ViewBag.PageName = "Gateway Messages";
                    break;
                case "GatewayDecodedMessages":
                    ViewBag.PageName = "Gateway Decoded Messages";
                    break;
                case "NodesEngine":
                    ViewBag.PageName = "Nodes Engine";
                    break;
            }

            return View();
        }
        
        



        public List<LogRecord> GetLogs(string logType)
        {
            if (logType == "All")
                return SystemController.logs.GetAllLogs();

            if (logType == "Errors")
                return SystemController.logs.GetErrorsLogs();

            LogRecordSource source;
            bool result = LogRecordSource.TryParse(logType, out source);
            if (!result)
                return null;

            return SystemController.logs.GetLogsOfSource(
                (LogRecordSource)Enum.Parse(typeof(LogRecordSource), logType));
        }



        [Authorize(UserClaims.LogsEditor)]

        public bool ClearLogs(string logType)
        {
            if (logType == "All")
            {
                SystemController.logs.ClearAllLogs();
                return true;
            }

            SystemController.logs.ClearLogsOfSource(
                (LogRecordSource)Enum.Parse(typeof(LogRecordSource), logType));
  

            return true;
        }
        

    }
}

WebController/Controllers/NodeEditorController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNodes.Nodes;
using MyNodes.Users;
using MyNodes.WebController.Code;
using MyNodes.WebController.ViewModels.NodeEditor;


namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.EditorObserver)]
    public class NodeEditorController : Controller
    {
        const string MAIN_PANEL_ID = "Main";

        private NodesEngine engine = SystemController.nodesEngine;


        public IActionResult Index(bool split)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");

            ViewBag.split = split;
            ViewBag.panelId = MAIN_PANEL_ID;

            ViewBag.Theme = SystemController.nodeEditorConfig.Theme;

            return View();
        }

        public IActionResult Panel(string id, bool split)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");


            ViewBag.split = split;

            if (id == null || id == MAIN_PANEL_ID)
                return RedirectToAction("Index");

            PanelNode panel = engine.GetPanelNode(id);

            if (panel == null)
                return NotFound();

            ViewBag.panelId = panel.Id;
            ViewBag.ownerPanelId = panel.PanelId;

            //create menu stack
            List<PanelNode> panelsStack = new List<PanelNode>();

            bool findNext = true;
            while (findNext)
            {
                panelsStack.Add(panel);
                if (panel.PanelId == MAIN_PANEL_ID)
                    findNext = false;
                else
                {
                    panel = engine.GetPanelNode(panel.PanelId);
                }
            }

            panelsStack.Reverse();
            ViewBag.panelsStack = panelsStack;

            ViewBag.Theme = SystemController.nodeEditorConfig.Theme;


            return View("Index");
        }


        public IActionResult Split(string id)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");

            if (id == null)
                ViewBag.route = "";
            else
                ViewBag.route = "Panel/" + id;
            return View();
        }

        public IActionResult NodesDescription()
        {
            List<Nodes.Node> nodes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(s => s.GetTypes())
                 .Where(t => t.IsSubclassOf(typeof(Nodes.Node)) && !t.IsAbstract)
                .Select(t => (Nodes.Node)Activator.CreateInstance(t)).ToList();

            nodes = nodes.OrderBy(x => x.Category + x.Type).ToList();

            List<NodeDescription> descrition = nodes.Select(node => new NodeDescription
            {
                category = node.Category,
                type = node.Type,
                description = node.GetNodeDescription()
            }).ToList();

            return View(descrition);
        }
    }
}

WebController/Views/Dashboard/Chart.cshtml
@model MyNodes.Nodes.UiChartNode

@{
    ViewBag.Title = Model.Settings["Name"].Value;
}
<br/>
<div class="ui container">

    @*<a asp-action="Log" asp-route-id="@ViewBag.nodeId" asp-route-id2="@ViewBag.sensorId" class="ui button right floated">Show Log</a>*@

    <h2 class="chartName">@ViewBag.Title</h2>

    <p>
        < <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
    </p>
    <div class="ui divider"></div>





    <div class="ui raised segments">
        <div class="ui secondary clearing segment">
            <b class="chartName">@ViewBag.Title</b>
            <button type="button" class='ui right floated small button' id="share-button"><b>Share</b></button>
            <button type="button" class="ui right floated small button" id="clear-button">Clear</button>
        </div>
        <div class="ui segment">
            <div id="infoPanel">
                Requesting data...
            </div>
            <br />
            <div id="chartPanel" style="display: none;">
                <div id="visualization"></div>
                <br />



                <div class="ui form">
                    <div class="ui fields">
                        <div class="ui field">
                            <label>Auto scroll:</label>
                            <select id="autoscroll" onchange="onAutoscrollChange()">
                                <option value="none" selected>None</option>
                                <option value="continuous">Continuous</option>
                                @*<option value="discrete">Discrete</option>*@
                                <option value="static">Static</option>
                            </select>
                        </div>

                        <div class="ui field">
                            <label>Style:</label>
                            <select id="charttype" onchange="onCharTypeChange()">
                                <option value="bars" selected>Bars</option>
                                <option value="splines">Splines</option>
                                <option value="shadedsplines">Shaded Splines</option>
                                <option value="lines">Lines</option>
                                <option value="shadedlines">Shaded Lines</option>
                                <option value="dots">Dots</option>
                            </select>
                        </div>

                        <div class="ui field">
                            <br>

                            <div class="ui basic buttons">
                                <button type="button" class='ui button' onclick="showAll()">
                                    <b>Zoom All</b>
                                </button>
                                <button type="button" class='ui button' onclick="showNow()">
                                    <b>Zoom Now</b>
                                </button>
                            </div>
                        </div>

                    </div>
                </div>



            </div>
        </div>
    </div>


    <div class="ui modal" id="shareModal">
        <div class="header">
            Chart share URL
        </div>
        <div class="content">
            <div class="ui form">
                <div class="field">
                    <label>URL:</label>
                    <textarea rows="3" id="url"></textarea>
                </div>
            </div>
        </div>
        <div class="actions">
            <div class="ui positive right button">
                OK
            </div>
        </div>
    </div>



</div>

@section styles{
    <link href="~/lib/vis/dist/vis.min.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/lib/vis/dist/vis.min.js"></script>

    <script type="text/javascript">
        var this_panel_id = "@ViewBag.panelId";
        var nodeId = '@Model.Id';

        var urlStart = @ViewBag.start;
        var urlEnd = @ViewBag.end;

        var autoScroll = "none";
        var charType = "bars";

        @if (ViewBag.autoscroll != null)
        {
            @:autoScroll = "@ViewBag.autoscroll";
        }


        @if (ViewBag.style != null)
        {
            @:charType = "@ViewBag.style";
       }

        $('#autoscroll').dropdown();
        $('#charttype').dropdown();

    </script>

    <script src="~/js/dashboard-chart-page.js"></script>
}

WebController/Views/Dashboard/Index.cshtml
@{
    if (ViewBag.panelId == "Home")
    {
        ViewBag.Title = "Dashboard";
    }
    else
    {
        ViewBag.Title = ViewBag.PanelName;
    }
}


<div class="ui container">

    @if (ViewBag.panelId == "Home")
    {
        <a asp-controller="NodeEditor" asp-action="Index" class="ui button right floated">Editor</a>

    }
    else
    {
        <a asp-controller="NodeEditor" asp-action="Panel" asp-route-id="@ViewBag.panelId" class="ui button right floated">Editor</a>
    }




    <h2>@ViewBag.Title</h2>
    <p>
        @if (ViewBag.panelId == "Home")
        {
            <a asp-action="List">Panels</a>
        }
        else
        {
            @:<
            <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
            @:<
            <a asp-action="List">Panels</a>

        }
    </p>
    <div class="ui divider"></div>

    <div class="ui message" id="empty-message" style="display: none">
        <p>
            @if (ViewBag.panelId == "Home")
            {
                @: Dashboard is empty. To create controls, go to the
                <a asp-controller="NodeEditor" asp-action="Index">Node Editor</a>@:.
            }
            else
            {
                @: Panel is empty. To create controls, go to the
                <a asp-controller="NodeEditor" asp-action="Panel" asp-route-id="@ViewBag.panelId">Node Editor</a>@:.
            }
        </p>
    </div>



    <div class="ui stackable centered grid" id="panelsContainer">
    </div>

</div>
<br />




<script id="panelTemplate" type="text/x-handlebars-template">
    <div class="column" id="panel-{{PanelId}}" style="width:360px; max-width:360px">
        <div class="ui raised segments">

            <div class="ui secondary clearing segment">
                <div class="ui two column grid">
                    <div class="fourteen wide column">
                        <b><span id="panelTitle-{{PanelId}}"></span></b>
                    </div>
                    <div class="two wide right aligned column">
                        <i class="square outline icon" id="activity-{{PanelId}}"></i>
                    </div>
                </div>
            </div>

            <div id="uiContainer-{{PanelId}}" class="content">
            </div>
        </div>
    </div>
</script>




<script id="labelTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="labelName-{{Id}}"></span>
        <div class="ui right floated basic disabled button nonbutton">
            <span class="ui blue basic label" id="labelValue-{{Id}}"></span>
        </div>
    </div>
</script>

<script id="stateTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="stateName-{{Id}}"></span>
        <div class="ui right floated basic disabled button nonbutton">
            <i class="big blue toggle on icon" id="state-on-{{Id}}" style="display:none"></i>
            <i class="big toggle off icon" id="state-off-{{Id}}" style="display:none"></i>
            <i class="big red toggle off icon" id="state-null-{{Id}}" style="display:none"></i>
        </div>
    </div>
</script>


<script id="textBoxTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="textBoxName-{{Id}}"></span>
        <div class="ui form text-box-form">
            <div class="ui field">
                <div class="ui small action input">
                    <input type="text" id="textBoxText-{{Id}}">
                    <button type="button" class="ui small button" id="textBoxSend-{{Id}}">Send</button>
                </div>
            </div>
        </div>
    </div>
</script>


<script id="logTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="logName-{{Id}}"></span>
        <button type="button" class="ui right floated tiny button" id="clear-log-{{Id}}">Clear</button>
        <br />
        <div class="ui segment" style="overflow-y: scroll; height: 150px;" id="log-{{Id}}"></div>
    </div>
</script>


<script id="progressTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="progressName-{{Id}}"></span>
        <div class="ui blue small progress" id="progressBar-{{Id}}">
            <div class="bar">
                <div class="progress"></div>
            </div>
        </div>
    </div>
</script>

<script id="buttonTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <button class="ui right floated small button" id="button-{{Id}}">
            &nbsp <span id="buttonName-{{Id}}"></span> &nbsp
        </button>
    </div>
</script>

<script id="toggleButtonTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <button class="ui right floated small toggle button" id="button-{{Id}}">
            &nbsp <span id="buttonName-{{Id}}"></span> &nbsp
        </button>
    </div>
</script>

<script id="switchTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="switchName-{{Id}}"></span>
        <div class="ui right floated basic  button nonbutton">
            <label class="switch">
                <input type="checkbox" class="switch-input" id="switch-{{Id}}">
                <span class="switch-label" data-on="On" data-off="Off"></span>
                <span class="switch-handle"></span>
            </label>
        </div>
    </div>
</script>

<script id="sliderTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="sliderName-{{Id}}"></span>
        <br />
        <div id="slider-{{Id}}"></div>
    </div>
</script>


<script id="rgbSlidersTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="sliderName-{{Id}}"></span>
        <br />
        <div id="slider-{{Id}}-r" class="spacebottom"></div>
        <div id="slider-{{Id}}-g" class="spacebottom"></div>
        <div id="slider-{{Id}}-b"></div>
    </div>
</script>

<script id="rgbwSlidersTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="sliderName-{{Id}}"></span>
        <br />
        <div id="slider-{{Id}}-r" class="spacebottom"></div>
        <div id="slider-{{Id}}-g" class="spacebottom"></div>
        <div id="slider-{{Id}}-b" class="spacebottom"></div>
        <div id="slider-{{Id}}-w"></div>
    </div>
</script>


<script id="chartTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <div class="ui mini right floated basic buttons">
            @*<button type="button" class="ui button" id="chart-clear-{{Id}}">Clr</button>*@
            <button type="button" class="ui button" id="chart-style-{{Id}}">Style</button>
            <button type="button" class="ui button" id="chart-all-{{Id}}">All</button>
            <button type="button" class="ui button" id="chart-now-{{Id}}">Now</button>
            <a href="/Dashboard/Chart/{{Id}}" class="ui button" id="chart-open-{{Id}}">Open</a>
        </div>
        <span id="chartName-{{Id}}"></span>
        <br />
        <br />
        <div id="chart-panel-{{Id}}-">
            <div id="chart-body-{{Id}}"></div>
        </div>

    </div>
</script>


<script id="timerTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="timer-name-{{Id}}"></span>
        <div class="ui small right floated basic buttons">
            <a href="/UITimer/Tasks/{{Id}}" class="ui button" id="timer-open-{{Id}}">Open</a>
        </div>
    </div>
</script>


<script id="voiceTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="voiceName-{{Id}}"></span>
    </div>
</script>

<script id="audioTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="audioName-{{Id}}"></span>
    </div>
</script>

@*html template for state switch UI node*@
<script id="stateSwitchTemplate" type="text/x-handlebars-template">
    <div class="ui attached clearing segment" id="node-{{Id}}">
        <span id="stateSwitchName-{{Id}}"></span>
        <div class="ui right floated basic  button nonbutton">
            <label class="switch">
                <input type="checkbox" class="switch-input" id="stateSwitch-{{Id}}">
                <span class="switch-label" data-on="On" data-off="Off"></span>
                <span class="switch-handle"></span>
            </label>
        </div>
    </div>
</script>

@section styles{
    <link href="~/lib/vis/dist/vis.min.css" rel="stylesheet" />
}


@section scripts
{
    <script>
        var this_panel_id = "@ViewBag.panelId";
    </script>
    <script src="~/lib/vis/dist/vis.min.js"></script>

    <script src="~/js/mysensors.js"></script>

    <script asp-src-include="~/js/dashboard/*.js"></script>
}

WebController/Views/Dashboard/List.cshtml
@using MyNodes.Nodes
@model IEnumerable<MyNodes.Nodes.PanelNode>

@{
    ViewBag.Title = "Panels";
}

<br />
<div class="ui container">

    <h2>@ViewBag.Title</h2>

    <p>
        < <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
    </p>
    <div class="ui divider"></div>



    <div style="padding-left: 20px">
        <h4>
            @if (ViewBag.showMainPanel)
            {
                <a asp-action="Panel" asp-route-id="Main">Main Panel</a><br/>
                <div class="ui divider"></div>
            }

            @foreach (PanelNode panel in Model)
            {
                <a asp-action="Panel" asp-route-id="@panel.Id">@panel.Settings["Name"].Value</a><br/>
                <div class="ui divider"></div>
            }
        </h4>

    </div>

</div>

WebController/Views/Dashboard/Log.cshtml
@using MyNodes.Gateways.MySensors
@model List<MyNodes.Gateways.MySensors.SensorData>

@{
    ViewBag.Title = ViewBag.description + " History";
}


<div class="ui container">

    <a asp-action="Chart" asp-route-id="@ViewBag.nodeId" asp-route-id2="@ViewBag.sensorId" class="ui button right floated">Show Chart</a>

    <h2>@ViewBag.Title</h2>

    <p>
        < <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
    </p>
    <div class="ui divider"></div>





    <div class="ui raised segments">
        <div class="ui secondary clearing segment">
            <b>@ViewBag.Title</b>
            <button type="button" class="ui right floated small button" id="clear-button">Clear</button>
        </div>
        <div class="ui attached segment">
            
            @if (!Model.Any())
            {
                @:There are no history. Log shows realtime data only. Check node <a href="/Node/Settings/@ViewBag.uiNodeId">settings</a>
                <br/>
            }

            <table class="ui striped table">
                <thead>
                <tr>
                    <th scope="col">
                        Date
                    </th>
                    <th scope="col">
                        State
                    </th>
                </tr>
                </thead>
                <tbody id="history-table">
                @foreach (SensorData item in Model)
                {
                    <tr>
                        <td>@item.dateTime</td>
                        <td>@item.state</td>
                    </tr>
                }
                </tbody>

                @*todo table pagination*@
                @*<tfoot>
                    <tr>

                        <th colspan="3">
                            <div class="ui pagination menu">
                                <a class="icon item">
                                    <i class="left chevron icon"></i>
                                </a>
                                <a class="item">1</a>
                                <a class="item">2</a>
                                <a class="item">3</a>
                                <a class="item">4</a>
                                <a class="icon item">
                                    <i class="right chevron icon"></i>
                                </a>
                            </div>
                        </th>


                    </tr>
                </tfoot>*@
            </table>
        </div>
        </div>





  


</div>

<br />


@section scripts
{
    <script type="text/javascript">
        var sensorId = '@ViewBag.sensorId';
        var nodeId = '@ViewBag.nodeId';
    </script>
    <script src="~/js/history-log-page.js"></script>
}