WebController/Controllers/LogsController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNodes.Users;
using MyNodes.WebController.Code;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.LogsObserver)]

    public class LogsController: Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Show",new { id = "System"});
        }


        public IActionResult Show(string id)
        {
            ViewBag.LogType = id;
            ViewBag.PageName = id;

            switch (id)
            {
                case "GatewayState":
                    ViewBag.PageName = "Gateway State";
                    break;
                case "GatewayMessages":
                    ViewBag.PageName = "Gateway Messages";
                    break;
                case "GatewayDecodedMessages":
                    ViewBag.PageName = "Gateway Decoded Messages";
                    break;
                case "NodesEngine":
                    ViewBag.PageName = "Nodes Engine";
                    break;
            }

            return View();
        }
        
        



        public List<LogRecord> GetLogs(string logType)
        {
            if (logType == "All")
                return SystemController.logs.GetAllLogs();

            if (logType == "Errors")
                return SystemController.logs.GetErrorsLogs();

            LogRecordSource source;
            bool result = LogRecordSource.TryParse(logType, out source);
            if (!result)
                return null;

            return SystemController.logs.GetLogsOfSource(
                (LogRecordSource)Enum.Parse(typeof(LogRecordSource), logType));
        }



        [Authorize(UserClaims.LogsEditor)]

        public bool ClearLogs(string logType)
        {
            if (logType == "All")
            {
                SystemController.logs.ClearAllLogs();
                return true;
            }

            SystemController.logs.ClearLogsOfSource(
                (LogRecordSource)Enum.Parse(typeof(LogRecordSource), logType));
  

            return true;
        }
        

    }
}

WebController/Controllers/NodeController.cs
/*  MyNetSensors 
    Copyright (C) 2015 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Configuration;
using Microsoft.AspNet.Mvc;


using MyNetSensors.Gateways;
using MyNetSensors.LogicalNodes;
using MyNetSensors.NodesTasks;
using MyNetSensors.Repositories.EF.SQLite;
using MyNetSensors.SerialControllers;


namespace MyNetSensors.WebController.Controllers
{
    public class NodeController : Controller
    {


      //  IHubContext clientsHub;
        private IGatewayRepository gatewayDb;

        public NodeController()
        {
            gatewayDb = SerialController.gatewayDb;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var nodes = gatewayDb.GetNodes();
            return View(nodes);
        }

        [HttpGet]
        public ActionResult Settings(int id)
        {
            Node node = gatewayDb.GetNode(id);
            if (node == null)
                return HttpNotFound();

            foreach (var sensor in node.sensors)
            {
                if (String.IsNullOrEmpty(sensor.description))
                    sensor.description = sensor.GetSimpleName1();
            }

            return View(node);
        }

        [HttpPost]
        public ActionResult Settings()
        {
            int id = Int32.Parse(Request.Form["Id"]);
            Node node = gatewayDb.GetNode(id);
            string nodename = Request.Form["nodename"];
            if (nodename == "")
                nodename = null;
            node.name = nodename;
            foreach (var sensor in node.sensors)
            {

                string sensordescription = Request.Form["sensordescription-" + sensor.sensorId];
                if (sensordescription == "")
                    sensordescription = null;
                sensor.description = sensordescription;


                bool invertData = Request.Form["invertData-" + sensor.sensorId] != "false";
                bool remapEnabled = Request.Form["remapData-" + sensor.sensorId] != "false";
                string remapFromMin = Request.Form["remapFromMin-" + sensor.sensorId];
                string remapFromMax = Request.Form["remapFromMax-" + sensor.sensorId];
                string remapToMin = Request.Form["remapToMin-" + sensor.sensorId];
                string remapToMax = Request.Form["remapToMax-" + sensor.sensorId];
                sensor.invertData = invertData;
                sensor.remapEnabled = remapEnabled;
                sensor.remapFromMin = remapFromMin;
                sensor.remapFromMax = remapFromMax;
                sensor.remapToMin = remapToMin;
                sensor.remapToMax = remapToMax;
            }
            gatewayDb.UpdateNodeSettings(node);

            GatewayAPIController gatewayApi = new GatewayAPIController();
            gatewayApi.UpdateNodeSettings(node);


            return RedirectToAction("Control", "Gateway");
            // return View(node);
        }

        public ActionResult Remove(int id)
        {
            Node node = gatewayDb.GetNode(id);
            if (node == null)
                return HttpNotFound();


            GatewayAPIController gatewayApi = new GatewayAPIController();
            gatewayApi.RemoveNode(node.Id);

            gatewayDb.RemoveNode(node.Id);



            INodesTasksRepository tasksDb = SerialController.nodesTasksDb;

            foreach (var sensor in node.sensors)
            {
                tasksDb.RemoveTasks(sensor.nodeId, sensor.sensorId);
            }

            gatewayApi.UpdateNodesTasks();



            return RedirectToAction("Control", "Gateway");
        }

    }
}

WebController/Controllers/NodesEditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using MyNetSensors.Gateways;
using LiteGraph;
using Microsoft.AspNet.Authorization;
using Microsoft.Extensions.Configuration;
using MyNetSensors.Nodes;
using MyNetSensors.Repositories.EF.SQLite;
using MyNetSensors.Users;
using MyNetSensors.WebController.Code;
using Newtonsoft.Json;


namespace MyNetSensors.WebController.Controllers
{
    [Authorize(UserClaims.EditorObserver)]
    public class NodesEditorController : Controller
    {
        const string MAIN_PANEL_ID = "Main";

        private NodesEngine engine = SystemController.nodesEngine;


        public IActionResult Index(bool split)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");

            ViewBag.split = split;
            ViewBag.panelId = MAIN_PANEL_ID;

            return View();
        }

        public IActionResult Panel(string id, bool split)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");


            ViewBag.split = split;

            if (id == null || id== MAIN_PANEL_ID)
                return RedirectToAction("Index");

            PanelNode panel = engine.GetPanelNode(id);

            if (panel == null)
                return HttpNotFound();

            ViewBag.panelId = panel.Id;
            ViewBag.ownerPanelId = panel.PanelId;

            //create menu stack
            List<PanelNode> panelsStack = new List<PanelNode>();

            bool findNext = true;
            while (findNext)
            {
                panelsStack.Add(panel);
                if (panel.PanelId == MAIN_PANEL_ID)
                    findNext = false;
                else
                {
                    panel = engine.GetPanelNode(panel.PanelId);
                }
            }

            panelsStack.Reverse();
            ViewBag.panelsStack = panelsStack;


            return View("Index");
        }


        public IActionResult Split(string id)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");

            if (id == null)
                ViewBag.route = "";
            else
                ViewBag.route = "Panel/" + id;
            return View();
        }
    }
}

WebController/Controllers/TasksController.cs
/*  MyNetSensors 
    Copyright (C) 2015 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using Microsoft.AspNet.Mvc;


using MyNetSensors.Gateways;
using MyNetSensors.LogicalNodes;
using MyNetSensors.Nodes;
using MyNetSensors.SerialControllers;
using MyNetSensors.WebController.Code;

namespace MyNetSensors.WebController.Controllers
{
    public class TasksController : Controller
    {
        private UITimerNodesEngine tasksEngine;
        private LogicalNodesEngine engine;

        public TasksController()
        {
            tasksEngine = SerialController.uiTimerNodesEngine;
            engine = SerialController.logicalNodesEngine;
        }

        public ActionResult List(string id)
        {
            UITimer node = engine.GetNode(id) as UITimer;

            if (node == null)
                return HttpNotFound();

            ViewBag.NodeId = node.Id;
            ViewBag.Name = node.Name;

            List<UITimerTask> tasks = tasksEngine.GetTasksForNode(id);

            return View(tasks);
        }


        [HttpGet]
        public ActionResult New(string id)
        {
            UITimer node = engine.GetNode(id) as UITimer;

            if (node == null)
                return HttpNotFound();

            ViewBag.NodeId = node.Id;
            ViewBag.Name = node.Name;

            UITimerTask task = new UITimerTask
            {
                NodeId = id,
                ExecutionDate = DateTime.Now,
                RepeatingInterval = 1000,
                Enabled = true
            };

            return View(task);
        }

        [HttpPost]
        public ActionResult New(UITimerTask task)
        {
            task.IsRepeating = Request.Form["isRepeating"] != "false";

            bool result = tasksEngine.AddTask(task);
            if (!result)
                return HttpBadRequest();

            return RedirectToAction("List", new { id = task.NodeId});
        }



        [HttpGet]
        public ActionResult Edit(int id)
        {
            UITimerTask task = tasksEngine.GetTask(id);

            if (task == null)
                return HttpNotFound();

            UITimer node = engine.GetNode(task.NodeId) as UITimer;

            if (node == null)
                return HttpNotFound();

            ViewBag.Name = node.Name;

            return View(task);
        }

        [HttpPost]
        public ActionResult Edit(UITimerTask task)
        {
            task.IsRepeating = Request.Form["isRepeating"] != "false";

            bool result = tasksEngine.UpdateTask(task);
            if (!result)
                return HttpBadRequest();

            return RedirectToAction("List", new { id = task.NodeId });
        }

        public ActionResult Remove(int id)
        {
            bool result = tasksEngine.RemoveTask(id);
            if (!result)
                return HttpBadRequest();

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("List");
        }

        public ActionResult Enable(int id)
        {
            UITimerTask task = tasksEngine.GetTask(id);

            if (task == null)
                return HttpNotFound();

            task.Enabled = true;

            bool result = tasksEngine.UpdateTask(task);
            if (!result)
                return HttpBadRequest();

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("List");
        }

        public ActionResult Disable(int id)
        {
            UITimerTask task = tasksEngine.GetTask(id);

            if (task == null)
                return HttpNotFound();

            task.Enabled = false;

            bool result = tasksEngine.UpdateTask(task);
            if (!result)
                return HttpBadRequest();

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("List");
        }

        public ActionResult ExecuteNow(int id)
        {
            bool result = tasksEngine.ExecuteNowTask(id);
            if (!result)
                return HttpBadRequest();

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("List");
        }


        public ActionResult RemoveAll(string id)
        {
            bool result = tasksEngine.RemoveTasksForNode(id);
            if (!result)
                return HttpBadRequest();

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("List");
        }


        public ActionResult RemoveCompleted(string id)
        {
            bool result = tasksEngine.RemoveCompletedTasksForNode(id);
            if (!result)
                return HttpBadRequest();

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("List");
        }


    }
}

WebController/Views/Gateway/Control.cshtml
@{
    ViewBag.Title = "Control Nodes";
}

<br />
<div class="ui container">

    <h2>@ViewBag.Title</h2>
    <p>
        <a asp-controller="NodesEditor" asp-action="Index">Editor</a> | 
        <a asp-controller="Tasks" asp-action="List">Tasks</a> |
        <a asp-controller="Node" asp-action="List">Settings</a>
    </p>
    <div class="ui divider"></div>

    <div class="ui four cards" id="nodesContainer" style="display: none;">
    </div>

</div>
<br/>


<script id="nodeTemplate" type="text/x-handlebars-template">
    <div class="ui card" id="nodePanel{{Id}}" style="min-width: 250px; max-width: 250px;">

        <div class="ui attached block header">
            <div class="left floated" id="nodeTitle{{Id}}">
                Node {{Id}}
            </div>
            <div class="right floated">
                <img src="@Url.Content("~/images/nodes/activity.gif")" id="activity{{Id}}" class="ui right floated" style="display: none;" />
            </div>
        </div>

        <div class="content">
            {{#if name}} {{name}} <br /> {{/if}}

            <div id="nodeBody{{Id}}"></div>
        </div>


        <div id="sensorsContainer{{Id}}" class="content">
        </div>

        <div class="ui bottom attached content" id="footer{{Id}}">
            <div class="left floated">
                {{#if batteryLevel}} Battery: <span id="nodeBattery{{Id}}"> {{batteryLevel}} </span>{{/if}}
            </div>
            <div class="right floated">
                <div class="ui dropdown">
                    <i class="sidebar icon"></i>
                    <div class="menu" id="nodeMenu{{Id}}">
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>




<script id="sensorTemplate" type="text/x-handlebars-template">
    <div class="" id="sensorPanel{{sensor-id this}}">

        <div class="left floated">
            <span id="sensorTitle{{sensor-id this}}">{{sensor-title this}}</span><br />

        </div>
        <div class="right floated">
            <div id="dataPanel{{sensor-id this}}">
            </div>
        </div>


        <br />
        <br />
    </div>
</script>



<script id="toggleTemplate" type="text/x-handlebars-template">
    <label class="switch">
        <input type="checkbox" class="switch-input" name="toggle-{{sensor-id this}}">
        <span class="switch-label" data-on="On" data-off="Off"></span>
        <span class="switch-handle"></span>
    </label>

</script>

<script id="sliderTemplate" type="text/x-handlebars-template">
    <div id="slider" name="slider-{{sensor-id this}}"></div>
</script>

<script id="rgbSlidersTemplate" type="text/x-handlebars-template">
    <div id="slider" name="slider-{{sensor-id this}}-r"></div>
    <div id="slider" name="slider-{{sensor-id this}}-g"></div>
    <div id="slider" name="slider-{{sensor-id this}}-b"></div>

</script>

<script id="rgbwSlidersTemplate" type="text/x-handlebars-template">
    <div id="slider" name="slider-{{sensor-id this}}-r"></div>
    <div id="slider" name="slider-{{sensor-id this}}-g"></div>
    <div id="slider" name="slider-{{sensor-id this}}-b"></div>
    <div id="slider" name="slider-{{sensor-id this}}-w"></div>
</script>

<script id="irSendTemplate" type="text/x-handlebars-template">
    <br />
    <div class="input-group">
        <input type="text" class="form-control" placeholder="IR code..." name="textbox-{{sensor-id this}}">
        <span class="input-group-btn">
            <button class="ui button" type="button" name="button-{{sensor-id this}}">Send</button>
        </span>
    </div>
</script>

<script id="nodeMenuTemplate" type="text/x-handlebars-template">
    <a class="item" href="../Node/Settings/{{Id}}">Settings</a>
    <div class="divider"></div>

    <div class="item">
        <i class="dropdown icon"></i>
        Hisotry
        <div class="menu" id="dropdownMenuHistory{{sensor-id this}}">
            {{#each sensors}}
            <a class="item" href="../History/Chart/{{this.nodeId}}/{{this.sensorId}}">{{sensor-title this}} History</a>
            {{/each}}
        </div>
    </div>
    <div class="divider"></div>

    <div class="item">
        <i class="dropdown icon"></i>
        Tasks
        <div class="menu" id="dropdownMenuTasks{{sensor-id this}}">
            {{#each sensors}}
            <a class="item" href="../Tasks/List/{{this.nodeId}}/{{this.sensorId}}">{{sensor-title this}} Tasks</a>
            {{/each}}
        </div>
    </div>


</script>



@section scripts
{
    <script src="~/js/mysensors.js"></script>
    <script src="~/js/mynetsensors-control-page.js"></script>
}

WebController/Views/Gateway/Log.cshtml
<br />

<div class="panel panel-default">
    <div class="panel-heading">
        Messages log
        <button type="button" class="btn btn-default pull-right" id="clear-log">
            <span class="glyphicon glyphicon-erase" aria-hidden="true"></span>
            Clear Log
        </button><br><br>


    </div>
    <div class="panel-body" style="overflow-y: scroll;" id="log">
    </div>

</div>


@section scripts
        {
    @Scripts.Render("~/bundles/signalr")
    <script src="~/signalr/hubs"></script>

    <script>
        $(function () {
            var gatewayHub = $.connection.gatewayHub;

            $('#clear-log').on('click', function () {
                gatewayHub.server.clearLog();
            });

            gatewayHub.client.onMessageRecievedEvent = function (message) {
                $('#log').append(message + "<br/>");
                $('#log').animate({ scrollTop: $('#log').get(0).scrollHeight }, 200);
            };

            gatewayHub.client.onMessageSendEvent = function (message) {
                $('#log').append(message + "<br/>");
                $('#log').animate({ scrollTop: $('#log').get(0).scrollHeight }, 200);
            };

            gatewayHub.client.returnLog = function (log) {
                $('#log').html(log);
                $('#log').animate({ scrollTop: $('#log').get(0).scrollHeight }, 200);
            };

            gatewayHub.client.onClearMessages = function (log) {
                $('#log').html(null);
                $('#log').animate({ scrollTop: $('#log').get(0).scrollHeight }, 200);
            };

            $.connection.hub.start().done(function () {
                gatewayHub.server.getLog();
            });

            $(function () {
                var window_height = $(window).height(),
                content_height = window_height - 280;
                $('#log').height(content_height);
            });

            $(window).resize(function () {
                var window_height = $(window).height(),
                content_height = window_height - 280;
                $('#log').height(content_height);
            });
        });


    </script>
}

WebController/Views/Gateway/Messages.cshtml
<br />

<div class="panel panel-default">
    <div class="panel-heading">
        Gateway Messages
        <button type="button" class="btn btn-default pull-right" id="clear-log">
            <span class="glyphicon glyphicon-erase" aria-hidden="true"></span>
            Clear Messages
        </button><br><br>


    </div>
    <div class="panel-body" style="overflow-y: scroll;" id="log">
    </div>

</div>


@section scripts
{
    <script src="~/js/mysensors.js"></script>
    <script src="~/js/mynetsensors-messages-page.js"></script>
}

WebController/Views/Gateway/NodesControl.cshtml
@{
    ViewBag.Title = "Nodes Control";
}

<h2>Nodes Control</h2>

<div class="row" id="nodesContainer" style="display: none;">
</div>

<div class="col-xs-12 col-sm-4 col-md-3" id="nodeTemplate" style="display: none;">
    <div class="panel panel-default">
        <div class="panel-heading">
            <img src="~/Content/Images/activity.gif" id="activity" class="pull-right" style="display: none;" />
            <div id="nodeTitle">

            </div>
        </div>

        <div class="panel-body">
   
            <span id="nodeBody"></span>
            <br/>
            <ul class="list-group" id="sensorsContainer"></ul>
            @*<a href="#" class="btn btn-default btn-sm pull-right" role="button" id="settingsButton">
                <span class='glyphicon glyphicon-menu-hamburger' aria-hidden='true'></span>
            </a>*@
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle pull-right" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class='glyphicon glyphicon-menu-hamburger' aria-hidden='true'></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu" id="dropdownMenuList">
                    
                </ul>
            </div>
        </div>

    </div>
</div>


@section styles
{

    <link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-switch.css" rel="stylesheet">
    <link href="~/Content/animate.min.css" rel="stylesheet">

}

@section scripts
{
    @Scripts.Render("~/bundles/signalr")
    <script src="~/signalr/hubs"></script>

    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/switch")

    @Scripts.Render("~/bundles/noty")
    @Scripts.Render("~/bundles/mysensors")
    @Scripts.Render("~/bundles/mynetsensors-control-page")


    <script>

    </script>
}

WebController/Views/Gateway/NodesView.cshtml
<h2>Nodes View</h2>

<div class="row" id="nodesContainer" style="display: none;">
</div>

<div class="col-xs-6 col-sm-4 col-md-3" id="nodeTemplate" style="display: none;">
    <div class="panel panel-default">
        <div class="panel-heading" id="nodeTitle">
            Node title
        </div>
        <div class="panel-body">
            <span id="nodeBody">Node body</span>
            <br/>
            <ul class="list-group" id="sensorsContainer"></ul>
        </div>
    </div>
</div>

@section styles
{
    <link href="~/Content/animate.min.css" rel="stylesheet">
}

@section scripts
{
    @Scripts.Render("~/bundles/signalr")
    <script src="~/signalr/hubs"></script>

    @Scripts.Render("~/bundles/moment")

    @Scripts.Render("~/bundles/noty")
    @Scripts.Render("~/bundles/mysensors")
    @Scripts.Render("~/bundles/mynetsensors-view-page")

    <script>
     
    </script>
}

WebController/Views/Gateway/Observe.cshtml
@{
    ViewBag.Title = "Observe Nodes";
}

<br />
<div class="ui container">

    <h2>@ViewBag.Title</h2>

    <div>
        @*<a asp-controller="Config" asp-action="Gateway">Gateway</a> |*@
        <br />
    </div>
    <div class="ui divider"></div>


    <div class="ui four column grid" id="nodesContainer" style="display: none;">
    </div>


</div>
<br />

<script id="nodeTemplate" type="text/x-handlebars-template">
    <div class="column" id="nodePanel{{Id}}" style="min-width: 290px;">
        <h4 class="ui top attached inverted header" id="nodeTitle{{Id}}">
            @*<h4 class="ui top attached block header id="nodeTitle{{Id}}">*@
            <span class="ui floated left">
                Node id: {{Id}}
            </span>
        </h4>
        <div class="ui attached segment">
            <div id="nodeBody{{Id}}">
                {{#if name}} Name: {{name}} <br /> {{/if}}
                {{#if version}} Version: {{version}} <br />{{/if}}
                {{#if registered}} Registered: {{fullDate registered}} <br />{{/if}}
                {{#if lastSeen}} Last seen: <span id="nodeLastSeen{{Id}}"> {{fullDate lastSeen}} </span><br />{{/if}}
                Repeating: {{yes-no isRepeatingNode}}<br />
                {{#if batteryLevel}} Battery: <span id="nodeBattery{{Id}}"> {{batteryLevel}} </span><br />{{/if}}
            </div>
            <br />
            <div class="ui segments" id="sensorsContainer{{Id}}"></div>
        </div>
    </div>
</script>

<script id="sensorTemplate" type="text/x-handlebars-template">
    <div class="ui segment" id="sensorPanel{{sensor-id this}}">
        Sensor Id: {{sensorId}} <br />
        Type: <span id="sensorType{{sensor-id this}}"> {{sensor-type this}} </span><br />
        {{#if description}} Description: {{description}} <br />{{/if}}
        Data Type: <span id="dataType{{sensor-id this}}"> </span><br />
        State: <span id="state{{sensor-id this}}"> </span><br />
    </div>
</script>



@section scripts
{

    <script src="~/js/mysensors.js"></script>
    <script src="~/js/mynetsensors-observe-page.js"></script>
}